on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: wget https://nodejs.org/dist/latest/win-x86/node.exe
      - run: wget https://nodejs.org/dist/latest/node-v20.8.0-linux-x64.tar.gz
      - run: tar -xzf node-v20.8.0-linux-x64.tar.gz
      - run: rm node-v20.8.0-linux-x64.tar.gz
      - run: cp node-v20.8.0-linux-x64/bin/node .
      - run: rm -R node-v20.8.0-linux-x64/
